shell = "/bin/fish"

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 4, y = 0 }
dynamic_padding = true

[cursor]
style = "Block"

[font]
normal = { family = "monospace" }
size = 11
