import = ["/home/chauncey/.config/alacritty/themes/tokyonight_night.toml"]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font]
builtin_box_drawing = true
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "monospace"
style = "Regular"

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[mouse.double_click]
threshold = 300

[mouse.triple_click]
threshold = 300

[scrolling]
history = 15000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "none"
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 110
lines = 30

[window.padding]
x = 0
y = 0
