server {
    listen 80;
    server_name _;

    root /var/www/cgit;
    index cgit.cgi;

    location / {
        include fastcgi_params;
        fastcgi_pass unix:/run/fcgiwrap/fcgiwrap.socket;
        fastcgi_param SCRIPT_FILENAME /var/www/cgit/cgit.cgi;
    }

    access_log /var/log/nginx/cgit.access.log;
    error_log /var/log/nginx/cgit.error.log;
}
