#!/usr/bin/python3

import dbus

def main():
  bus = dbus.SystemBus()
  obj = bus.get_object('org.bluez', '/')
  om = dbus.Interface(obj, dbus_interface='org.freedesktop.DBus.ObjectManager')
  devices = om.GetManagedObjects()
  for dev in devices.values():
    if b := dev.get('org.bluez.Battery1'):
      name = dev['org.bluez.Device1']['Alias']
      percent = int(b['Percentage'])
      print(name, f'{percent}%')

if __name__ == '__main__':
  main()
