#!/bin/sh

exec swayidle -w timeout 180 'light -S 50' timeout 300 'swaylock -f' timeout 360 'swaymsg "output * power off"' \
        resume 'swaymsg "output * power on" && light -S 100' before-sleep 'playctl pause' before-sleep 'swaylock'

