###不支持参数后注释，须另起一行
###不允许选项和值之间存在多余的空格

########################################
#⇘⇘分菜单 —— 用户着色器

# 着色器目录扫描路径
shader_dir=~~/shaders/
# 着色器文件扩展名白名单，逗号分隔，留空则不过滤。特殊值 * 表示无扩展名
shader_exts=*,glsl,hook
# <set（默认）|toggle|append|pre|remove> 点击着色器条目的操作
shader_action_prefer=set

# <session（默认）|persist> 预设的保存模式
shader_preset_save=session
# 预设缓存文件的存储目录
shader_cache_dir=~~/

########################################
#⇘⇘分菜单 —— 字幕行

# 是否拼接多行字幕（会触发截断）
subtext_merge=no

########################################
#⇘⇘分菜单 —— 属性检查（须要 FFmpeg）

# 是否直接显示属性值（显著影响性能）
prop_show_values=no
# <show（默认）|copy> 点击条目的操作。输出到OSD 或 复制到剪贴板
prop_action_prefer=show

########################################
#⇘⇘分菜单 —— 阵列式缩略图（须要脚本 #缩略图引擎#）

# 磁贴间隔
vcs_padding=30
# <0...25> 最大磁贴数量
vcs_tiles=12
# 章节模式
vcs_chapter_mode=no
