interface-name: wlan0
routing-mark: 1
sniffer:
  enable: true
  sniffing:
    - tls
    - http
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
allow-lan: false
log-level: silent
mode: global
external-controller: '127.0.0.1:9090'
secret: ''
dns:
  enable: true
  listen: '127.0.0.1:1053'
  ipv6: true
  enhanced-mode: redir-host
  default-nameserver:
    - 8.8.8.8
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
