vim.pack.add({ {
  src = _G.gh("ibhagwan/fzf-lua"),
} })

local ok, fzf = pcall(require, "fzf-lua")

if ok then
  fzf.setup()

  -- search
  vim.keymap.set({ "n" }, '<leader>s"', function()
    FzfLua.registers()
  end, { desc = "Registers" })
  vim.keymap.set({ "n" }, "<leader>s/", function()
    FzfLua.search_history()
  end, { desc = "Search History" })
  vim.keymap.set({ "n" }, "<leader>sa", function()
    FzfLua.autocmds()
  end, { desc = "Autocmds" })
  vim.keymap.set({ "n" }, "<leader>sb", function()
    FzfLua.lines()
  end, { desc = "Buffer Lines" })
  vim.keymap.set({ "n" }, "<leader>sc", function()
    FzfLua.command_history()
  end, { desc = "Command History" })
  vim.keymap.set({ "n" }, "<leader>sC", function()
    FzfLua.commands()
  end, { desc = "Commands" })
  vim.keymap.set({ "n" }, "<leader>sd", function()
    FzfLua.diagnostics_workspace()
  end, { desc = "Diagnostics" })
  vim.keymap.set({ "n" }, "<leader>sD", function()
    FzfLua.diagnostics_document()
  end, { desc = "Buffer Diagnostics" })
  vim.keymap.set({ "n" }, "<leader>sf", function()
    FzfLua.files()
  end, { desc = "Find files" })
  vim.keymap.set({ "n" }, "<leader>sh", function()
    FzfLua.helptags()
  end, { desc = "Help Pages" })
  vim.keymap.set({ "n" }, "<leader>sH", function()
    FzfLua.highlights()
  end, { desc = "Highlights" })
  vim.keymap.set({ "n" }, "<leader>sj", function()
    FzfLua.jumps()
  end, { desc = "Jumps" })
  vim.keymap.set({ "n" }, "<leader>sk", function()
    FzfLua.keymaps()
  end, { desc = "Keymaps" })
  vim.keymap.set({ "n" }, "<leader>sl", function()
    FzfLua.loclist()
  end, { desc = "Location List" })
  vim.keymap.set({ "n" }, "<leader>sm", function()
    FzfLua.marks()
  end, { desc = "Marks" })
  vim.keymap.set({ "n" }, "<leader>sM", function()
    FzfLua.manpages()
  end, { desc = "Man Pages" })
  vim.keymap.set({ "n" }, "<leader>sq", function()
    FzfLua.quickfix()
  end, { desc = "Quickfix List" })
  vim.keymap.set({ "n" }, "<leader>sR", function()
    FzfLua.resume()
  end, { desc = "Resume" })
  vim.keymap.set({ "n" }, "<leader>su", function()
    FzfLua.undotree()
  end, { desc = "Undo History" })

  vim.keymap.set({ "n" }, "<leader>uC", function()
    FzfLua.colorschemes()
  end, { desc = "Colorschemes" })
end
